version: '3.8'

services:
  db-seminar:
    image: mysql:8.0
    container_name: db-seminar
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_GUEST_USER=${MYSQL_GUEST_USER}
      - MYSQL_GUEST_PASSWORD=${MYSQL_GUEST_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - seminar-network

networks:
  seminar-network:
    driver: bridge