spring:
  datasource:
    primary:
      url: jdbc:mysql://${MYSQL_HOST:db-seminar}:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

    readonly:
      url: jdbc:mysql://${MYSQL_HOST:db-seminar}:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      username: ${MYSQL_GUEST_USER}
      password: ${MYSQL_GUEST_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false

logging:
  level:
    root: INFO
    com.sailorham.stcs: INFO
    org.hibernate.SQL: INFO