spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:db-seminar}:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true

  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false

logging:
  level:
    root: INFO
    com.sailorham.stcs: INFO
    org.hibernate.SQL: INFO